return {
    Characters = {
        Naruto = {
            Order = 1, 
            Price = 25, 
            SellPrice = 12, 
            CashAmount = 1, 
            Rarity = "Common", 
            SpawnRarity = 1800, 
            FakeName = "Maruto"
        }, 
        Luffy = {
            Order = 2, 
            Price = 250, 
            SellPrice = 125, 
            CashAmount = 3, 
            Rarity = "Common", 
            SpawnRarity = 1500, 
            FakeName = "Luffee"
        }, 
        Gojo = {
            Order = 3, 
            Price = 500, 
            SellPrice = 250, 
            CashAmount = 5, 
            Rarity = "Common", 
            SpawnRarity = 1250, 
            FakeName = "Gujo"
        }, 
        Yeager = {
            Order = 4, 
            Price = 750, 
            SellPrice = 375, 
            CashAmount = 7, 
            Rarity = "Common", 
            SpawnRarity = 1000, 
            FakeName = "Yeagen"
        }, 
        Izuku = {
            Order = 5, 
            Price = 1200, 
            SellPrice = 600, 
            CashAmount = 10, 
            Rarity = "Uncommon", 
            SpawnRarity = 900, 
            FakeName = "Azuku"
        }, 
        Denji = {
            Order = 6, 
            Price = 2000, 
            SellPrice = 1000, 
            CashAmount = 15, 
            Rarity = "Uncommon", 
            SpawnRarity = 850, 
            FakeName = "Renji"
        }, 
        Tanjiro = {
            Order = 7, 
            Price = 3000, 
            SellPrice = 1500, 
            CashAmount = 25, 
            Rarity = "Uncommon", 
            SpawnRarity = 800, 
            FakeName = "Sanjiro"
        }, 
        Goku = {
            Order = 8, 
            Price = 4000, 
            SellPrice = 2000, 
            CashAmount = 30, 
            Rarity = "Uncommon", 
            SpawnRarity = 700, 
            FakeName = "Roku"
        }, 
        Sasuke = {
            Order = 9, 
            Price = 5000, 
            SellPrice = 2500, 
            CashAmount = 40, 
            Rarity = "Rare", 
            SpawnRarity = 600, 
            FakeName = "Basuke"
        }, 
        Isagi = {
            Order = 10, 
            Price = 7500, 
            SellPrice = 3750, 
            CashAmount = 55, 
            Rarity = "Rare", 
            SpawnRarity = 550, 
            FakeName = "Asagi"
        }, 
        Saitama = {
            Order = 11, 
            Price = 10000, 
            SellPrice = 5000, 
            CashAmount = 75, 
            Rarity = "Rare", 
            SpawnRarity = 500, 
            FakeName = "Faitama"
        }, 
        Ichigo = {
            Order = 12, 
            Price = 12500, 
            SellPrice = 6250, 
            CashAmount = 100, 
            Rarity = "Rare", 
            SpawnRarity = 450, 
            FakeName = "Ichiko"
        }, 
        Hinata = {
            Order = 13, 
            Price = 15000, 
            SellPrice = 7500, 
            CashAmount = 125, 
            Rarity = "Rare", 
            SpawnRarity = 425, 
            FakeName = "Gone"
        }, 
        ["Luffy 5"] = {
            Order = 14, 
            Price = 20000, 
            SellPrice = 10000, 
            CashAmount = 150, 
            Rarity = "Epic", 
            SpawnRarity = 400, 
            FakeName = "Evolved Ruffy"
        }, 
        Killua = {
            Order = 15, 
            Price = 25000, 
            SellPrice = 12500, 
            CashAmount = 200, 
            Rarity = "Epic", 
            SpawnRarity = 350, 
            FakeName = "Kallua"
        }, 
        Roronoa = {
            Order = 16, 
            Price = 35000, 
            SellPrice = 17500, 
            CashAmount = 300, 
            Rarity = "Epic", 
            SpawnRarity = 300, 
            FakeName = "Roroloa"
        }, 
        Kaneki = {
            Order = 17, 
            Price = 50000, 
            SellPrice = 25000, 
            CashAmount = 500, 
            Rarity = "Epic", 
            SpawnRarity = 250, 
            FakeName = "Baneki"
        }, 
        Madara = {
            Order = 18, 
            Price = 75000, 
            SellPrice = 37500, 
            CashAmount = 750, 
            Rarity = "Epic", 
            SpawnRarity = 200, 
            FakeName = "Ladara"
        }, 
        Sukuna = {
            Order = 19, 
            Price = 100000, 
            SellPrice = 50000, 
            CashAmount = 1000, 
            Rarity = "Legendary", 
            SpawnRarity = 100, 
            FakeName = "Sukupa"
        }, 
        Gon = {
            Order = 20, 
            Price = 200000, 
            SellPrice = 100000, 
            CashAmount = 1200, 
            Rarity = "Legendary", 
            SpawnRarity = 90, 
            FakeName = "Nihata"
        }, 
        Ackerman = {
            Order = 21, 
            Price = 300000, 
            SellPrice = 150000, 
            CashAmount = 1500, 
            Rarity = "Legendary", 
            SpawnRarity = 80, 
            FakeName = "Ackernan"
        }, 
        Kagenou = {
            Order = 22, 
            Price = 500000, 
            SellPrice = 250000, 
            CashAmount = 1800, 
            Rarity = "Legendary", 
            SpawnRarity = 70, 
            FakeName = "Kakenou"
        }, 
        Igris = {
            Order = 23, 
            Price = 750000, 
            SellPrice = 375000, 
            CashAmount = 2000, 
            Rarity = "Legendary", 
            SpawnRarity = 60, 
            FakeName = "Kakenou"
        }, 
        Beru = {
            Order = 24, 
            Price = 1000000, 
            SellPrice = 500000, 
            CashAmount = 2500, 
            Rarity = "Legendary", 
            SpawnRarity = 50, 
            FakeName = "Peru"
        }, 
        ["Jin-Woo"] = {
            Order = 25, 
            Price = 5000000, 
            SellPrice = 2500000, 
            CashAmount = 3500, 
            Rarity = "Mythic", 
            SpawnRarity = 25, 
            FakeName = "Jin-Voo"
        }, 
        Kaiju = {
            Order = 26, 
            Price = 10000000, 
            SellPrice = 5000000, 
            CashAmount = 4000, 
            Rarity = "Mythic", 
            SpawnRarity = 20, 
            FakeName = "Kaifo"
        }, 
        Yoriichi = {
            Order = 27, 
            Price = 15000000, 
            SellPrice = 7500000, 
            CashAmount = 5000, 
            Rarity = "Mythic", 
            SpawnRarity = 15, 
            FakeName = "Yoriiqhi"
        }, 
        Okarun = {
            Order = 28, 
            Price = 30000000, 
            SellPrice = 15000000, 
            CashAmount = 7000, 
            Rarity = "Mythic", 
            SpawnRarity = 10, 
            FakeName = "Okaran"
        }, 
        Kakashi = {
            Order = 29, 
            Price = 50000000, 
            SellPrice = 25000000, 
            CashAmount = 10000, 
            Rarity = "Mythic", 
            SpawnRarity = 7, 
            FakeName = "Kagashi"
        }, 
        Ryuk = {
            Order = 30, 
            Price = 200000000, 
            SellPrice = 100000000, 
            CashAmount = 20000, 
            Rarity = "Secret", 
            SpawnRarity = 3, 
            FakeName = "Reuk"
        }, 
        Toji = {
            Order = 31, 
            Price = 250000000, 
            SellPrice = 125000000, 
            CashAmount = 25000, 
            Rarity = "Secret", 
            SpawnRarity = 2, 
            FakeName = "Togi"
        }, 
        Zero = {
            Order = 32, 
            Price = 300000000, 
            SellPrice = 150000000, 
            CashAmount = 35000, 
            Rarity = "Secret", 
            SpawnRarity = 1, 
            FakeName = "Zaro"
        }
    }
};
