local v0 = {
    Template = {
        Max_Health = 0, 
        Health_Regen = 0, 
        Stamina = 0, 
        Stamina_Regen = 0, 
        Exp = 0, 
        Drop_Rate = 0, 
        All_Damage_Boost = 0, 
        Strength_Boost = 0, 
        Sword_Damage = 0, 
        Speed_Boost = 0, 
        Item_Stats_Name = "", 
        Drop = {
            Ouwigahara = 2, 
            MugenTrain = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Claws", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.35
            }
        }, 
        Inventory_Category = "Weapon/Hat/Mask/Scarf/Necklace/Uniform/Haorie/Lantern/Shirt/Bottom/Potion/Material/Other"
    }, 
    Item_Category_Order = {
        "All", 
        "Weapon", 
        "Hat", 
        "Mask", 
        "Scarf", 
        "Necklace", 
        "Shirt", 
        "Pants", 
        "Uniform", 
        "Haorie", 
        "Lantern", 
        "Potion", 
        "Material", 
        "Other"
    }, 
    WearableStatItems = {
        "Hat", 
        "Mask", 
        "Scarf", 
        "Necklace", 
        "Shirt", 
        "Pants", 
        "Uniform", 
        "Haorie", 
        "Lantern"
    }, 
    ["Green Katana"] = {
        Sword_Damage = 1, 
        Drop = {
            Shop = 500
        }, 
        Data = {
            {
                Settings = {
                    Name = "Green Katana", 
                    Type = "Tool", 
                    Rarity = "Common", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.35
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Golden Katana"] = {
        Sword_Damage = 1, 
        Drop = {
            Shop = 1069
        }, 
        Data = {
            {
                Settings = {
                    Name = "Golden Katana", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.35
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Lightning Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.01, 
        Drop = {
            ["Tier 1"] = 8, 
            ["Tier 2"] = 8, 
            ["Tier 10"] = 8, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Lightning Katana", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.6
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Wind Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.01, 
        Drop = {
            ["Tier 1"] = 8, 
            ["Tier 2"] = 8, 
            ["Tier 10"] = 8, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Wind Katana", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.65
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Water Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.01, 
        Drop = {
            ["Tier 1"] = 8, 
            ["Tier 2"] = 8, 
            ["Tier 10"] = 8, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Water Katana", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.6
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Giyu's Water Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.02, 
        Drop = {
            ["Tier 1"] = 8, 
            ["Tier 2"] = 8, 
            ["Tier 10"] = 8, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Giyu's Water Katana", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.75
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Insect Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.02, 
        Drop = {
            ["Tier 1"] = 5, 
            ["Tier 2"] = 5, 
            ["Tier 10"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Insect Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.75
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Flame Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.04, 
        Drop = {
            ["Tier 3"] = 3, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Flame Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.75
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Mist Katana"] = {
        Sword_Damage = 2, 
        Breathing_Percent_Damage = 0.04, 
        Drop = {
            ["Tier 3"] = 3, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Mist Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.75
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    Scythe = {
        Weapon_Damage = 1, 
        Drop = {
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Scythe", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.5
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Metal Scythe"] = {
        Weapon_Damage = 2, 
        Block = 1, 
        Drop = {
            Ouwigahara_Shop = 3250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Metal Scythe", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    Claws = {
        Weapon_Damage = 2, 
        Drop = {
            Shop = 250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Claws", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.35
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Skull Claws"] = {
        Weapon_Damage = 3, 
        Drop = {
            Ouwigahara_Shop = 2750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Skull Claws", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Waterfall Katana"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            Ouwigahara_Shop = 3750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Waterfall Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Tornadic Katana"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            Ouwigahara_Shop = 3750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tornadic Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Volcanic Katana"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            Ouwigahara_Shop = 3750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Volcanic Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Thundercloud Katana"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            Ouwigahara_Shop = 3750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Thundercloud Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Cloud Katana"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            Ouwigahara_Shop = 3750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Cloud Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Butterfly Katana"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            Ouwigahara_Shop = 3750
        }, 
        Data = {
            {
                Settings = {
                    Name = "Butterfly Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Beast Katanas"] = {
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            ["Tier 3"] = 0.25, 
            ["Tier 5"] = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Beast Katanas", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Skull Scythe"] = {
        Weapon_Damage = 3, 
        Drop = {
            MugenTrain = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Skull Scythe", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.25
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Bone Claws"] = {
        Weapon_Damage = 3, 
        Drop = {
            MugenTrain = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Bone Claws", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.25
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Champion Katana"] = {
        Breathing_Percent_Damage = 0.07, 
        Sword_Damage = 10, 
        Crit_Chance = 0.05, 
        Npc_Damage_Buff = 0.1, 
        Drop = {
            ["Ouwigahara Leaderboard"] = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Champion Katana", 
                    Type = "Tool", 
                    Rarity = "Limited", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 2.15
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    Combat = {
        Fist_Damage = 1, 
        Drop = {
            Quest = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Fist", 
                    Type = "Tool", 
                    Rarity = "Common", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.65
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    Soryu = {
        Fist_Damage = 2, 
        Drop = {
            Quest = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Soryu", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.65
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["War Fans"] = {
        Weapon_Damage = 3.5, 
        Drop = {
            ["Tier 5"] = 1
        }, 
        Data = {
            {
                Settings = {
                    Name = "War Fans", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 1.75
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Snow Katana"] = {
        Sword_Damage = 4, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            ["Tier 5"] = 1
        }, 
        Data = {
            {
                Settings = {
                    Name = "Snow Katana", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 3
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Sound Katanas"] = {
        Sword_Damage = 4, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            ["Tier 5"] = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Sound Katanas", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 3
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Devourer Katana"] = {
        Tier = {
            [0] = {
                Sword_Damage = 3
            }, 
            [1] = {
                Sword_Damage = 4, 
                Block = 2
            }, 
            [2] = {
                Sword_Damage = 6, 
                Block = 3
            }, 
            [3] = {
                Sword_Damage = 8, 
                Block = 5, 
                Devour = 0.1, 
                Breathing_Percent_Damage = 0.25
            }
        }, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Katana", 
                    Type = "Tool", 
                    Rarity = "Devourer", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 5, 
                Tier = 0, 
                Blood = 0
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Polar Katana"] = {
        Tier = {
            [0] = {
                Sword_Damage = 3, 
                Block = 2
            }, 
            [1] = {
                Sword_Damage = 4, 
                Block = 3
            }, 
            [2] = {
                Sword_Damage = 6, 
                Block = 4
            }, 
            [3] = {
                Sword_Damage = 8, 
                Block = 6, 
                FrostBite = 0.05, 
                Breathing_Percent_Damage = 0.25
            }
        }, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Polar Katana", 
                    Type = "Tool", 
                    Rarity = "Polar", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 5, 
                Tier = 0, 
                Essence = 0
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Devourer Scythe"] = {
        Tier = {
            [0] = {
                Weapon_Damage = 3
            }, 
            [1] = {
                Weapon_Damage = 4, 
                Block = 2
            }, 
            [2] = {
                Weapon_Damage = 6, 
                Block = 3
            }, 
            [3] = {
                Weapon_Damage = 8, 
                Block = 4, 
                Devour = 0.1
            }
        }, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Scythe", 
                    Type = "Tool", 
                    Rarity = "Devourer", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 5, 
                Tier = 0, 
                Blood = 0
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Polar Scythe"] = {
        Tier = {
            [0] = {
                Weapon_Damage = 3, 
                Block = 1
            }, 
            [1] = {
                Weapon_Damage = 4, 
                Block = 3
            }, 
            [2] = {
                Weapon_Damage = 6, 
                Block = 4
            }, 
            [3] = {
                Weapon_Damage = 8, 
                Block = 5, 
                FrostBite = 0.05
            }
        }, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Polar Scythe", 
                    Type = "Tool", 
                    Rarity = "Polar", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 5, 
                Tier = 0, 
                Essence = 0
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Devourer Fans"] = {
        Tier = {
            [0] = {
                Weapon_Damage = 3
            }, 
            [1] = {
                Weapon_Damage = 4, 
                Block = 1
            }, 
            [2] = {
                Weapon_Damage = 6, 
                Block = 2
            }, 
            [3] = {
                Weapon_Damage = 8, 
                Block = 4, 
                Devour = 0.1
            }
        }, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Fans", 
                    Type = "Tool", 
                    Rarity = "Devourer", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 5, 
                Tier = 0, 
                Blood = 0
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Polar Fans"] = {
        Tier = {
            [0] = {
                Weapon_Damage = 3, 
                Block = 1
            }, 
            [1] = {
                Weapon_Damage = 4, 
                Block = 2
            }, 
            [2] = {
                Weapon_Damage = 6, 
                Block = 3
            }, 
            [3] = {
                Weapon_Damage = 8, 
                Block = 5, 
                FrostBite = 0.05
            }
        }, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Polar Fans", 
                    Type = "Tool", 
                    Rarity = "Polar", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }, 
            {
                Health = {
                    10, 
                    10
                }, 
                Health_Mult = 5, 
                Tier = 0, 
                Essence = 0
            }
        }, 
        Inventory_Category = "Weapon"
    }, 
    ["Sabito's Mask"] = {
        Max_Health = 15, 
        Data = {
            {
                Settings = {
                    Name = "Sabito's Mask", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Stylish Mask"] = {
        Stamina = 40, 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Stylish Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Fox Mask"] = {
        Max_Health = 25, 
        Health_Regen = 0.15, 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Fox Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Flower Fox Mask"] = {
        Max_Health = 30, 
        Health_Regen = 0.2, 
        Drop = {
            Ouwigahara_Shop = 2250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Flower Fox Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Fawx Mask"] = {
        Max_Health = 40, 
        Health_Regen = 0.5, 
        Drop = {
            Ouwigahara_Shop = 2250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Fawx Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Urokodaki's Mask"] = {
        Max_Health = 30, 
        Stamina = 40, 
        Drop_Rate = 0.03, 
        Inventory_Category = "Mask", 
        Data = {
            {
                Settings = {
                    Name = "Urokodaki's Mask", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }
    }, 
    ["Panther Mask"] = {
        Max_Health = 60, 
        Health_Regen = 0.15, 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Panther Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Hiretsuna Kitsune Mask"] = {
        Stamina = -250, 
        Stamina_Regen = 0.35, 
        Speed_Boost = 0.05, 
        All_Damage_Boost = 0.025, 
        Drop = {
            MugenTrain = 1.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Hiretsuna Kitsune Mask", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Akuma no ie Mask"] = {
        Max_Health = 30, 
        Stamina_Regen = 0.1, 
        Strength_Boost = 1, 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Akuma no ie Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Orenjibisuto Mask"] = {
        Max_Health = 45, 
        Health_Regen = 0.1, 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Orenjibisuto Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Yatagarasu Mask"] = {
        Max_Health = 25, 
        Exp = 0.05, 
        Drop_Rate = 0.05, 
        Drop = {
            ["Tier 3"] = 0.25, 
            ["Tier 5"] = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Yatagarasu Mask", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Akuma Kurenza Mask"] = {
        Max_Health = 100, 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Akuma Kurenza Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Sealed Box"] = {
        Data = {
            {
                Settings = {
                    Name = "Sealed Box", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }
    }, 
    ["Foxie Mask"] = {
        Max_Health = 35, 
        Health_Regen = 0.5, 
        Drop = {
            Ouwigahara_Shop = 2250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Foxie Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Fox King Mask"] = {
        Health_Regen = 0.03, 
        Stamina = 20, 
        Stamina_Regen = 0.03, 
        Drop = {
            Ouwigahara_Shop = 2250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Fox King Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Blue Fox Mask"] = {
        Max_Health = 55, 
        Health_Regen = 0.1, 
        Drop = {
            Ouwigahara_Shop = 2250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Blue Fox Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Purple Foxie Mask"] = {
        Health_Regen = 0.03, 
        Stamina = 20, 
        Stamina_Regen = 0.03, 
        Drop = {
            Ouwigahara_Shop = 2250
        }, 
        Data = {
            {
                Settings = {
                    Name = "Purple Foxie Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Boar Head"] = {
        Max_Health = 45, 
        Speed_Boost = 0.05, 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Boar Head", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Champion Mask"] = {
        Max_Health = 160, 
        Health_Regen = 0.25, 
        All_Damage_Boost = 0.05, 
        Stamina = 50, 
        Stamina_Regen = 0.1, 
        Breathing_Percent_Damage = 0.02, 
        Crit_Chance = 0.01, 
        Npc_Damage_Buff = 0.025, 
        Drop = {
            ["Ouwigahara Leaderboard"] = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Champion Mask", 
                    Type = "Tool", 
                    Rarity = "Limited", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Polar Mask"] = {
        Essence_Multiplier = 0.2, 
        Max_Health = 80, 
        Stamina = 70, 
        All_Damage_Boost = 0.0225, 
        Weapon_Damage = 1, 
        Sword_Damage = 1, 
        Block = 4, 
        Drop = {
            ["Tier 5"] = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Polar Mask", 
                    Type = "Tool", 
                    Rarity = "Polar", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Devourer Mask"] = {
        Blood_Multiplier = 0.2, 
        Max_Health = 80, 
        Stamina = 70, 
        All_Damage_Boost = 0.0225, 
        Weapon_Damage = 1, 
        Sword_Damage = 1, 
        Block = 4, 
        Drop = {
            ["Tier 5"] = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Mask", 
                    Type = "Tool", 
                    Rarity = "Devourer", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Tigress Warding Mask"] = {
        Max_Health = 75, 
        Weapon_Damage = 3, 
        Block = 1, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 1.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tigress Warding Mask", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Banigaru Mask"] = {
        Stamina = 60, 
        Stamina_Regen = 0.15, 
        Speed_Boost = 0.15, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 1.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Banigaru Mask", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Tonakai Keikai Mask"] = {
        Max_Health = 90, 
        Block = 3, 
        Damage_Reduction = 0.05, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 1.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tonakai Keikai Mask", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Tactical Black Headband"] = {
        Breathing_Percent_Damage = 0.02, 
        Drop = {
            ["Tier 2"] = 2, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 3.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tactical Black Headband", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Bandaged Blindfold"] = {
        Max_Health = 30, 
        Strength_Boost = 1, 
        Drop = {
            ["Tier 3"] = 2, 
            ["Tier 5"] = 3.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Bandaged Blindfold", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Dark Smoke Visor"] = {
        Max_Health = 30, 
        Stamina_Regen = 0.1, 
        Stamina = 50, 
        Drop = {
            ["Tier 3"] = 2, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Dark Smoke Visor", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Gem Stone Eyepatch"] = {
        Max_Health = 30, 
        Sword_Damage = 1, 
        All_Damage_Boost = 0.01, 
        Drop = {
            ["Tier 3"] = 0.5, 
            ["Tier 5"] = 1
        }, 
        Data = {
            {
                Settings = {
                    Name = "Gem Stone Eyepatch", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Ominous Blindfold"] = {
        Max_Health = 15, 
        Strength_Boost = 2, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Ominous Blindfold", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Bandaged Mask"] = {
        Max_Health = 50, 
        Stamina = 50, 
        All_Damage_Boost = 0.005, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Bandaged Mask", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Mask"
    }, 
    ["Striped Green Scarf"] = {
        Max_Health = 65, 
        Health_Regen = 0.1, 
        Stamina = 20, 
        Sword_Damage = 1, 
        Drop = {
            MugenTrain = 5.25
        }, 
        Data = {
            {
                Settings = {
                    Name = "Striped Green Scarf", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["White Scarf"] = {
        Max_Health = 50, 
        Health_Regen = 0.2, 
        Stamina = 15, 
        Drop = {
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "White Scarf", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Black Hooded Scarf"] = {
        Max_Health = 55, 
        Health_Regen = 0.15, 
        Stamina = 20, 
        Drop = {
            Ouwigahara = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Black Hooded Scarf", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Brown Scarf"] = {
        Max_Health = 45, 
        Health_Regen = 0.1, 
        Stamina = 25, 
        Drop = {
            Ouwigahara = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Brown Scarf", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Red Scarf"] = {
        Health_Regen = 0.1, 
        Stamina = 20, 
        Strength_Boost = 1, 
        Max_Health = 65, 
        Drop = {
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Red Scarf", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Champion Scarf"] = {
        Max_Health = 120, 
        Health_Regen = 0.2, 
        Stamina = 60, 
        All_Damage_Boost = 0.025, 
        Strength_Boost = 3, 
        Sword_Damage = 3, 
        Breathing_Percent_Damage = 0.02, 
        Crit_Chance = 0.01, 
        Npc_Damage_Buff = 0.025, 
        Drop = {
            ["Ouwigahara Leaderboard"] = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Champion Scarf", 
                    Type = "Tool", 
                    Rarity = "Limited", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Black Caped Scarf"] = {
        Max_Health = 60, 
        Stamina = 60, 
        Drop = {
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Black Caped Scarf", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Vigilante Scarf"] = {
        Speed_Boost = 0.1, 
        Stamina = 50, 
        Stamina_Regen = 0.05, 
        Drop = {
            Ouwigahara = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Vigilante Scarf", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Uncertained Times Scarf"] = {
        Speed_Boost = -0.1, 
        Max_Health = 250, 
        Drop = {
            ["Tier 3"] = 3, 
            ["Tier 5"] = 4
        }, 
        Data = {
            {
                Settings = {
                    Name = "Uncertained Times Scarf", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Scarf"
    }, 
    ["Riyaku's Necklace"] = {
        Max_Health = 20, 
        Inventory_Category = "Necklace"
    }, 
    ["Mist Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Mist Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Swamp Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Swamp Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Flame Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            MugenTrain = 2.25
        }, 
        Data = {
            {
                Settings = {
                    Name = "Flame Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Shockwave Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            MugenTrain = 2.25
        }, 
        Data = {
            {
                Settings = {
                    Name = "Shockwave Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Arrow Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Arrow Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Butterfly Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            Ouwigahara = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Butterfly Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Water Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            Ouwigahara = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Water Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Thunder Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            Ouwigahara = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Thunder Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Beast Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Beast Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Wind Necklace"] = {
        Breathing_Percent_Damage = 0.025, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Wind Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Tamari Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tamari Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Dream Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            MugenTrain = 2.25
        }, 
        Data = {
            {
                Settings = {
                    Name = "Dream Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Blood Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            Ouwigahara = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Blood Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Reaper Necklace"] = {
        Art_Percent_Damage = 0.025, 
        Drop = {
            Ouwigahara = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Reaper Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Rusty Necklace"] = {
        Breathing_Percent_Damage = 0.01, 
        Art_Percent_Damage = 0.01, 
        Max_Health = 35, 
        Drop = {
            Ouwigahara = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Rusty Necklace", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Champion Necklace"] = {
        All_Damage_Boost = 0.1, 
        Crit_Chance = 0.01, 
        Npc_Damage_Buff = 0.025, 
        Drop = {
            ["Ouwigahara Leaderboard"] = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Champion Necklace", 
                    Type = "Tool", 
                    Rarity = "Limited", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Kesshoseki Necklace"] = {
        Max_Health = 75, 
        Stamina = 75, 
        Speed_Boost = 0.05, 
        Drop = {
            ["Tier 3"] = 2, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Kesshoseki Necklace", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Necklace"
    }, 
    ["Tamari Arms"] = {
        Item_Stats_Name = "Tamari_Arms", 
        Max_Health = 20, 
        Strength_Boost = 10
    }, 
    ["Nezuko's Bamboo Pacifier"] = {
        Max_Health = 25, 
        Item_Stats_Name = "bamboopacifier123asd", 
        Inventory_Category = "Mask"
    }, 
    Lantern = {
        Health_Regen = 0.05, 
        Drop = {
            Shop = 600
        }, 
        Data = {
            {
                Settings = {
                    Name = "Lantern", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Item_Stats_Name = "Night_Time_Lantern", 
        Inventory_Category = "Lantern"
    }, 
    ["Old Lantern"] = {
        Stamina_Regen = 0.05, 
        Health_Regen = 0.05, 
        Drop = {
            Ouwigahara = 10
        }, 
        Data = {
            {
                Settings = {
                    Name = "Old Lantern", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Item_Stats_Name = "Old_Night_Time_Lantern", 
        Inventory_Category = "Lantern"
    }, 
    ["Box Lantern"] = {
        Health_Regen = 0.1, 
        Drop = {
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Box Lantern", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Lantern"
    }, 
    ["Lantern Of Despair"] = {
        Health_Regen = 0.05, 
        Stamina_Regen = 0.15, 
        Drop = {
            MugenTrain = 4
        }, 
        Data = {
            {
                Settings = {
                    Name = "Lantern Of Despair", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Lantern"
    }, 
    ["Lantern Of Everlasting Glow"] = {
        Health_Regen = 0.15, 
        Stamina_Regen = 0.05, 
        Drop = {
            Ouwigahara = 4
        }, 
        Data = {
            {
                Settings = {
                    Name = "Lantern Of Everlasting Glow", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Lantern"
    }, 
    ["Straw Hat"] = {
        Sun_Immunity = 1, 
        Block = 5, 
        Max_Health = 50, 
        Item_Stats_Name = "demon_umbrella_equiped", 
        Drop = {
            ["Tier 1"] = 1, 
            ["Tier 2"] = 1, 
            ["Tier 10"] = 1, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Straw Hat", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Hat"
    }, 
    ["Black Bamboo Amigasa"] = {
        Max_Health = 50, 
        Strength_Boost = 1, 
        Stamina = 10, 
        Damage_Reduction = 0.01, 
        Drop = {
            Ouwigahara = 1
        }, 
        Data = {
            {
                Settings = {
                    Name = "Black Bamboo Amigasa", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Hat"
    }, 
    ["Samurai Maiden's Amigasa"] = {
        Max_Health = 250, 
        Strength_Boost = 2, 
        Stamina = 50, 
        Damage_Reduction = 0.05, 
        Drop = {
            MugenTrain = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Samurai Maiden's Amigasa", 
                    Type = "Tool", 
                    Rarity = "Supreme", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Hat"
    }, 
    ["Shinobu Haorie"] = {
        Max_Health = 100, 
        Item_Stats_Name = "Haorie_1", 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Shinobu Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 1, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Giyu Haorie"] = {
        Max_Health = 100, 
        Item_Stats_Name = "Haorie_2", 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Giyu Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 2, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Zenitsu Haorie"] = {
        Max_Health = 100, 
        Item_Stats_Name = "Haorie_3", 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Zenitsu Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 3, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Snow Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_16", 
        Drop = {
            MugenTrain_Legendary = 100, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Snow Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 16, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Tanjiro Haorie"] = {
        Max_Health = 100, 
        Item_Stats_Name = "Haorie_4", 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tanjiro Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 4, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Stylish Haorie"] = {
        Max_Health = 100, 
        Item_Stats_Name = "Haorie_5", 
        Drop = {
            ["Tier 1"] = 3, 
            ["Tier 2"] = 3, 
            ["Tier 10"] = 3, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Stylish Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 5, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Shadow Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_6", 
        Drop = {
            MugenTrain_Legendary = 100, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Shadow Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 6, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Black Lilly Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_7", 
        Drop = {
            Ouwigahara = 5, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Black Lilly Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 7, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Black Spider Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_8", 
        Drop = {
            MugenTrain_Legendary = 100, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Black Spider Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 8, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Dark Green Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_9", 
        Drop = {
            Ouwigahara = 5, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Dark Green Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 9, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Green Vine Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_10", 
        Drop = {
            Ouwigahara = 5, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Green Vine Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 10, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Olive Green Flower Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_11", 
        Drop = {
            MugenTrain_Legendary = 100, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Olive Green Flower Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 11, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Purple Flower Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_12", 
        Drop = {
            Ouwigahara = 5, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Purple Flower Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 12, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Sakura Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_13", 
        Drop = {
            Ouwigahara = 5, 
            MugenTrain_Legendary = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Sakura Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 13, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Sleeveless Dragon Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_14", 
        Drop = {
            MugenTrain_Legendary = 100, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Sleeveless Dragon Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 14, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Yellow Haorie"] = {
        Max_Health = 150, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_15", 
        Drop = {
            MugenTrain_Legendary = 100, 
            ["Tier 3"] = 2.5, 
            ["Tier 5"] = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Yellow Haorie", 
                    Type = "Haorie", 
                    Rarity = "Rare", 
                    Value = 15, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Champion Haorie"] = {
        Max_Health = 250, 
        Health_Regen = 0.25, 
        Stamina = 150, 
        Stamina_Regen = 0.1, 
        All_Damage_Boost = 0.05, 
        Breathing_Percent_Damage = 0.02, 
        Crit_Chance = 0.01, 
        Npc_Damage_Buff = 0.025, 
        Exp = 0.1, 
        Item_Stats_Name = "Haorie_500", 
        Drop = {
            ["Ouwigahara Leaderboard"] = 100
        }, 
        Data = {
            {
                Settings = {
                    Name = "Champion Haorie", 
                    Type = "Haorie", 
                    Rarity = "Limited", 
                    Value = 500, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Akai Kumo Haorie"] = {
        Max_Health = 50, 
        Stamina = 100, 
        Stamina_Regen = 0.05, 
        Item_Stats_Name = "Haorie_20", 
        Drop = {
            ["Tier 3"] = 0.5, 
            ["Tier 5"] = 1, 
            MugenTrain = 1.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Akai Kumo Haorie", 
                    Type = "Haorie", 
                    Rarity = "Mythic", 
                    Value = 20, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Boroboro Haorie"] = {
        Max_Health = 200, 
        Health_Regen = 0.05, 
        Item_Stats_Name = "Haorie_18", 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 2.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Boroboro Haorie", 
                    Type = "Haorie", 
                    Rarity = "Mythic", 
                    Value = 18, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Ichimatsu Haorie"] = {
        Max_Health = 100, 
        Exp = 0.05, 
        Drop_Rate = 0.05, 
        Item_Stats_Name = "Haorie_22", 
        Drop = {
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 2.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Ichimatsu Haorie", 
                    Type = "Haorie", 
                    Rarity = "Mythic", 
                    Value = 22, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Kanden Shi Haorie"] = {
        Stamina = 120, 
        Breathing_Percent_Damage = 0.05, 
        Speed_Boost = 0.05, 
        Item_Stats_Name = "Haorie_19", 
        Drop = {
            ["Tier 3"] = 1, 
            ["Tier 5"] = 2
        }, 
        Data = {
            {
                Settings = {
                    Name = "Kanden Shi Haorie", 
                    Type = "Haorie", 
                    Rarity = "Mythic", 
                    Value = 19, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Murasakiiro Sutoraipu Haorie"] = {
        Fist_Damage = 3, 
        Weapon_Damage = 3, 
        Art_Percent_Damage = 0.025, 
        Item_Stats_Name = "Haorie_21", 
        Drop = {
            ["Tier 3"] = 2, 
            ["Tier 5"] = 3
        }, 
        Data = {
            {
                Settings = {
                    Name = "Murasakiiro Sutoraipu Haorie", 
                    Type = "Haorie", 
                    Rarity = "Mythic", 
                    Value = 21, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Tokosen Haorie"] = {
        Speed_Boost = 0.15, 
        Health_Regen = 0.15, 
        Stamina_Regen = 0.15, 
        Item_Stats_Name = "Haorie_17", 
        Drop = {
            ["Tier 3"] = 2, 
            ["Tier 5"] = 3.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tokosen Haorie", 
                    Type = "Haorie", 
                    Rarity = "Mythic", 
                    Value = 17, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Rengoku Haorie"] = {
        All_Damage_Boost = 0.05, 
        Max_Health = 250, 
        Breathing_Percent_Damage = 0.05, 
        Stamina = 60, 
        Item_Stats_Name = "Haorie_23", 
        Drop = {
            ["Limited 1.5 Update"] = 550
        }, 
        Data = {
            {
                Settings = {
                    Name = "Rengoku Haorie", 
                    Type = "Haorie", 
                    Rarity = "Limited", 
                    Value = 23, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Haorie"
    }, 
    ["Akaza Top"] = {
        Max_Health = 300, 
        Strength_Boost = 4, 
        Art_Percent_Damage = 0.01, 
        Npc_Damage_Buff = 0.05, 
        Item_Stats_Name = "Top_9991", 
        Drop = {
            MugenTrain = 0.125
        }, 
        Data = {
            {
                Settings = {
                    Name = "Akaza Top", 
                    Type = "Top", 
                    Rarity = "Supreme", 
                    Value = 9991, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Shirt"
    }, 
    ["Akaza Bottom"] = {
        Stamina = 300, 
        Strength_Boost = 4, 
        Speed_Boost = 0.02, 
        Npc_Damage_Buff = 0.05, 
        Item_Stats_Name = "Bottom_9991", 
        Drop = {
            MugenTrain = 0.125
        }, 
        Data = {
            {
                Settings = {
                    Name = "Akaza Bottom", 
                    Type = "Bottom", 
                    Rarity = "Supreme", 
                    Value = 9991, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Pants"
    }, 
    ["Enmu Top"] = {
        Max_Health = 300, 
        Sword_Damage = 4, 
        Breathing_Percent_Damage = 0.05, 
        Npc_Damage_Buff = 0.05, 
        Item_Stats_Name = "Top_9992", 
        Drop = {
            MugenTrain = 0.125
        }, 
        Data = {
            {
                Settings = {
                    Name = "Enmu Top", 
                    Type = "Top", 
                    Rarity = "Supreme", 
                    Value = 9992, 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Shirt"
    }, 
    ["Enmu Bottom"] = {
        Max_Health = 250, 
        Speed_Boost = 0.02, 
        Sword_Damage = 4, 
        Npc_Damage_Buff = 0.05, 
        Item_Stats_Name = "Bottom_9992", 
        Drop = {
            MugenTrain = 0.125
        }, 
        Data = {
            {
                Settings = {
                    Name = "Enmu Bottom", 
                    Type = "Bottom", 
                    Rarity = "Supreme", 
                    Value = 9992, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Pants"
    }, 
    ["Inosuke Bottom"] = {
        Max_Health = 125, 
        Speed_Boost = 0.05, 
        Item_Stats_Name = "Bottom_9993", 
        Data = {
            {
                Settings = {
                    Name = "Inosuke Bottom", 
                    Type = "Bottom", 
                    Rarity = "Rare", 
                    Value = 9993, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Pants"
    }, 
    ["Douma Top"] = {
        Max_Health = 175, 
        Health_Regen = 0.1, 
        Exp = 0.025, 
        Weapon_Damage = 3, 
        Drop = {
            ["Tier 5"] = 0.5
        }, 
        Item_Stats_Name = "Top_9996", 
        Data = {
            {
                Settings = {
                    Name = "Douma Top", 
                    Type = "Top", 
                    Rarity = "Supreme", 
                    Value = 9996, 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Shirt"
    }, 
    ["Douma Bottom"] = {
        Stamina = 175, 
        Stamina_Regen = 0.1, 
        Drop_Rate = 0.025, 
        Weapon_Damage = 3, 
        Item_Stats_Name = "Bottom_9997", 
        Drop = {
            ["Tier 5"] = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Douma Bottom", 
                    Type = "Bottom", 
                    Rarity = "Supreme", 
                    Value = 9997, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Pants"
    }, 
    ["Devourer Top"] = {
        Blood_Multiplier = 0.5, 
        Max_Health = 280, 
        Stamina = 100, 
        All_Damage_Boost = 0.08, 
        Weapon_Damage = 1, 
        Sword_Damage = 1, 
        Damage_Reduction = 0.07, 
        Health_Regen = 0.15, 
        Npc_Damage_Buff = 0.025, 
        Item_Stats_Name = "Top_9997", 
        Drop = {
            MugenTrain = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Top", 
                    Type = "Top", 
                    Rarity = "Devourer", 
                    Value = 9997, 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Shirt"
    }, 
    ["Devourer Bottom"] = {
        Blood_Multiplier = 0.3, 
        Max_Health = 170, 
        Stamina = 50, 
        All_Damage_Boost = 0.025, 
        Weapon_Damage = 2, 
        Sword_Damage = 2, 
        Damage_Reduction = 0.07, 
        Health_Regen = 0.05, 
        Npc_Damage_Buff = 0.025, 
        Item_Stats_Name = "Bottom_9998", 
        Drop = {
            MugenTrain = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Bottom", 
                    Type = "Bottom", 
                    Rarity = "Devourer", 
                    Value = 9998, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Pants"
    }, 
    ["Polar Top"] = {
        Essence_Multiplier = 0.5, 
        Max_Health = 250, 
        Stamina = 130, 
        All_Damage_Boost = 0.05, 
        Weapon_Damage = 1, 
        Sword_Damage = 1, 
        Damage_Reduction = 0.07, 
        Health_Regen = 0.1, 
        Drop = {
            Ouwigahara = 0.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Polar Top", 
                    Type = "Top", 
                    Rarity = "Polar", 
                    Value = 9998, 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Shirt"
    }, 
    ["Polar Bottom"] = {
        Essence_Multiplier = 0.3, 
        Max_Health = 150, 
        Stamina = 70, 
        All_Damage_Boost = 0.035, 
        Weapon_Damage = 2, 
        Sword_Damage = 2, 
        Damage_Reduction = 0.07, 
        Health_Regen = 0.08, 
        Item_Stats_Name = "Bottom_9999", 
        Drop = {
            Ouwigahara = 0.25
        }, 
        Data = {
            {
                Settings = {
                    Name = "Polar Bottom", 
                    Type = "Bottom", 
                    Rarity = "Polar", 
                    Value = 9999, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Pants"
    }, 
    ["Winter Coat"] = {
        Max_Health = 100, 
        Item_Stats_Name = "NoCCShirt_winter_coat_shirt123asd", 
        Drop = {
            Shop = 6000
        }, 
        Data = {
            {
                Settings = {
                    Name = "Winter Coat", 
                    Type = "Shirt", 
                    Rarity = "Rare", 
                    Value = "winter_coat_shirt123asd", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Other"
    }, 
    ["Wind Pillar Uniform"] = {
        Speed_Boost = 0.05, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Wind Pillar Uniform", 
                    Type = "Uniform", 
                    Rarity = "UnCommon", 
                    Value = 1, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Uniform"
    }, 
    ["Stone Pillar Uniform"] = {
        Max_Health = 100, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Stone Pillar Uniform", 
                    Type = "Uniform", 
                    Rarity = "UnCommon", 
                    Value = 2, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Uniform"
    }, 
    ["Purple Uniform"] = {
        Stamina = 50, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Purple Uniform", 
                    Type = "Uniform", 
                    Rarity = "UnCommon", 
                    Value = 3, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Uniform"
    }, 
    ["Feminine Uniform"] = {
        All_Damage_Boost = 0.01, 
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Feminine Uniform", 
                    Type = "Uniform", 
                    Rarity = "UnCommon", 
                    Value = 4, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Uniform"
    }, 
    ["Tengen Uniform"] = {
        Speed_Boost = 0.15, 
        Exp = 0.05, 
        Max_Health = 80, 
        Stamina = 40, 
        Breathing_Percent_Damage = 0.05, 
        Drop = {
            ["Limited 1.5 Update"] = 500
        }, 
        Data = {
            {
                Settings = {
                    Name = "Tengen Uniform", 
                    Type = "Uniform", 
                    Rarity = "Limited", 
                    Value = 5, 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Uniform"
    }, 
    ["Stamina Elixir"] = {
        Drop = {
            ["Tier 1"] = 15, 
            ["Tier 2"] = 15, 
            ["Tier 10"] = 15
        }, 
        Data = {
            {
                Settings = {
                    Name = "Stamina Elixir", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Health Elixir"] = {
        Drop = {
            ["Tier 1"] = 15, 
            ["Tier 2"] = 15, 
            ["Tier 10"] = 15
        }, 
        Data = {
            {
                Settings = {
                    Name = "Health Elixir", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Health Regen Elixir"] = {
        Drop = {
            ["Tier 1"] = 10, 
            ["Tier 2"] = 10, 
            ["Tier 10"] = 10
        }, 
        Data = {
            {
                Settings = {
                    Name = "Jumbo Health Regen Elixir", 
                    Type = "Tool", 
                    Rarity = "UnCommon", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Jumbo Stamina Elixir"] = {
        Drop = {
            Ouwigahara = 50, 
            ["Tier 3"] = 50, 
            ["Tier 5"] = 50, 
            Ouwigahara_Shop = 50
        }, 
        Data = {
            {
                Settings = {
                    Name = "Jumbo Stamina Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Clan Spins Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Clan Spins Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Mastery Buff Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Mastery Buff Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Exp Buff Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Exp Buff Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Race Reset Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Race Reset Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Breath Reset Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Breath Reset Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Demon Spins Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Demon Spins Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Polar Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Polar Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Devourer Elixir"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Devourer Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Jumbo Health Elixir"] = {
        Drop = {
            Ouwigahara = 50, 
            ["Tier 3"] = 50, 
            ["Tier 5"] = 50, 
            Ouwigahara_Shop = 75
        }, 
        Data = {
            {
                Settings = {
                    Name = "Jumbo Health Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Jumbo Health Regen Elixir"] = {
        Drop = {
            Ouwigahara = 45, 
            ["Tier 3"] = 45, 
            ["Tier 5"] = 45, 
            Ouwigahara_Shop = 75
        }, 
        Data = {
            {
                Settings = {
                    Name = "Jumbo Health Regen Elixir", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    ["Muzan's Blood"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Muzan's Blood", 
                    Type = "Tool", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Potion"
    }, 
    Ore = {
        Drop = {
            ["Tier 1"] = 1, 
            ["Tier 2"] = 1, 
            ["Tier 3"] = 1.5, 
            ["Tier 5"] = 3, 
            ["Tier 10"] = 1
        }, 
        Data = {
            {
                Settings = {
                    Name = "Ore", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Mugen Train Ticket"] = {
        Drop = {
            MugenTrain = 12.5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Mugen Train Ticket", 
                    Type = "Collectible", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Other"
    }, 
    Ouwfish = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Ouwfish", 
                    Type = "Fish", 
                    Rarity = "UnCommon", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    Ouwfwesh = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Ouwfwesh", 
                    Type = "Fish", 
                    Rarity = "UnCommon", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    Ouwfash = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Ouwfash", 
                    Type = "Fish", 
                    Rarity = "UnCommon", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Demon Horn"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Demon Horn", 
                    Type = "Collectible", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Blood Stained Ingot"] = {
        Drop = {
            Ouwigahara = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Blood Stained Ingot", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Frigid Metal"] = {
        Drop = {
            Ouwigahara = 5
        }, 
        Data = {
            {
                Settings = {
                    Name = "Frigid Metal", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Living Flesh"] = {
        Drop = {
            MugenTrain = 10
        }, 
        Data = {
            {
                Settings = {
                    Name = "Living Flesh", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Orbed Glacier"] = {
        Drop = {
            MugenTrain = 10
        }, 
        Data = {
            {
                Settings = {
                    Name = "Orbed Glacier", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Frost Touched Cloth"] = {
        Drop = {
            ["Tier 3"] = 5, 
            ["Tier 5"] = 10
        }, 
        Data = {
            {
                Settings = {
                    Name = "Frost Touched Cloth", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Skinned Hide"] = {
        Drop = {
            ["Tier 3"] = 5, 
            ["Tier 5"] = 10
        }, 
        Data = {
            {
                Settings = {
                    Name = "Skinned Hide", 
                    Type = "Collectible", 
                    Rarity = "Mythic", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Blue Spider Lily"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Blue Spider Lily", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 1
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Material"
    }, 
    ["Fishing Rod"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Fishing Rod", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Other"
    }, 
    ["Bamboo Fishing Rod"] = {
        Drop = {}, 
        Data = {
            {
                Settings = {
                    Name = "Fishing Rod", 
                    Type = "Tool", 
                    Rarity = "Rare", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = false
            }
        }, 
        Inventory_Category = "Other"
    }, 
    Bandage = {
        Drop = {}, 
        Wen_Cost = 50, 
        Data = {
            {
                Settings = {
                    Name = "Bandage", 
                    Type = "Tool", 
                    Rarity = "Common", 
                    Id = 4
                }, 
                Amount = 1, 
                CanHaveMoreThenOne = true
            }
        }, 
        Inventory_Category = "Other"
    }
};
local v1 = {
    UnCommon = 30, 
    Rare = 60, 
    Mythic = 100, 
    Supreme = 120, 
    Polar = 150, 
    Devourer = 150, 
    Limited = 140
};
for v2, v3 in pairs(v0) do
    if v3.Data and v3.Data[1] and v3.Data[1].Settings.Rarity then
        local v4 = v1[v3.Data[1].Settings.Rarity];
        if v4 then
            v0[v2].Trade_Level = v4;
        end;
    end;
end;
return v0;
